name: QA for The Great Bet
on: push

jobs:
  # Label of the container job
  main:
    runs-on: ubuntu-latest
    container: node:lts

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run static analysis
        run: npm run lint -s
